-- This SQL script creates a 'users' table with the following fields:
-- - 'id': A unique identifier for each user (primary key), automatically incremented.
-- - 'username': The username of the user, which cannot be null.
-- - 'password': The password of the user, which cannot be null.
-- - 'created_at': The timestamp when the user was created, automatically set to the current time.
CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- This SQL command inserts a new record into the 'users' table with the following values:
-- - 'username': Sets the username to 'maciek'.
-- - 'password': Sets the password to 'test'.
-- The 'id' is automatically generated by the database (because of the SERIAL type).
-- The 'created_at' field is automatically set to the current timestamp.
INSERT INTO users username, password VALUES ('maciek', 'test');